### ISSUE TITLE
[SOLVED] Getting the "HeadlessException" error in a VM environment

### ISSUE THREAD

**Issue by pedlima** [mrmaxent/Maxent#18]
Hi,

So the code bellow runs in my VM server:

```
<?php

function run_maxent_and_get_image($speciesData) {
    $maxEntJarPath = __DIR__ . '/../assets/java/maxent.jar';
    $outputDirectory = __DIR__ . '/../resources/'; // Output directory for MaxEnt

    // Path to the input file for MaxEnt
    $inputFilePath = $outputDirectory . 'species_data.csv';
    
    // Open file handle to write
    $fileHandle = fopen($inputFilePath, 'w');
    if ($fileHandle === false) {
        echo "Failed to open file for writing.\n";
        return false; // Exit function if file opening fails
    }

    // Write the header for the CSV file
    fputcsv($fileHandle, ['species', 'longitude', 'latitude']);
    
    // Loop through each occurrence and write to the file
    foreach ($speciesData as $occurrence) {
        fputcsv($fileHandle, [$occurrence['species'], $occurrence['longitude'], $occurrence['latitude']]);
    }
    
    // Close the file handle
    fclose($fileHandle);

    // Prepare the command to run MaxEnt
    $command = escapeshellcmd("java -mx512m -Djava.awt.headless=true -jar \"$maxEntJarPath\" environmentallayers=$outputDirectory samplesfile=\"$inputFilePath\" outputdirectory=\"$outputDirectory\"");
    $command .= " 2>&1"; // Redirect stderr to stdout for comprehensive output capture

    // Execute MaxEnt and capture the output. Note: shell_exec() does not allow capturing return status.
    exec($command, $output, $returnVar);

    // Check execution status and log the output
    if ($returnVar !== 0) {
        echo "Command failed with status $returnVar:\n";
        foreach ($output as $line) {
            echo "$line\n";
        }
        return false;
    } else {
        echo "Command succeeded:\n";
        foreach ($output as $line) {
            echo "$line\n";
        }
        // Assuming MaxEnt generates PNG files, attempt to find one
        $imageFiles = glob($outputDirectory . '*.png');
        if (!empty($imageFiles)) {
            // Return the first image path found
            return $imageFiles[0];
        } else {
            echo "No output image found.\n";
            return false;
        }
    }
}

// Example usage of the function with the new data structure.
$imagePath = run_maxent_and_get_image([
    ['species' => 'bradypus_variegatus', 'longitude' => -65.4, 'latitude' => -10.3833],
    ['species' => 'bradypus_variegatus', 'longitude' => -65.3833, 'latitude' => -10.3833],
]);

if ($imagePath !== false) {
    echo "<img src='$imagePath' />";
} else {
    echo "<br>Error running MaxEnt or processing the data.";
}
?>

```

But unfortunately, this is the output of that code:

```
Command succeeded: Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204) at java.awt.Window.(Window.java:536) at java.awt.Frame.(Frame.java:420) at javax.swing.JFrame.(JFrame.java:233) at density.MaxEnt.createAndShowGUI(MaxEnt.java:65) at density.MaxEnt.access$000(MaxEnt.java:30) at density.MaxEnt$1.run(MaxEnt.java:51) at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) at java.awt.EventQueue.access$500(EventQueue.java:97) at java.awt.EventQueue$3.run(EventQueue.java:709) at java.awt.EventQueue$3.run(EventQueue.java:703) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) No output image found.
Error running MaxEnt or processing the data.
```

Do you guys know a way to fix this?

Thanks!

**Comment by pedlima** [comment]
For whoever reaches here, what solved my problem was first of all @bowbahdoe and he has just updated the maxent.jar file to work with the latest Java version right [here](https://github.com/bowbahdoe/Maxent).

This is a full working code for me:

```
<?php

function run_maxent() {
    // Define the MaxEnt JAR path and the output directory.
    $maxEntJarPath = __DIR__ . '/../assets/java/maxent.jar'; // Ensure this path is correct
    $outputDirectory = __DIR__ . '/../resources/'; // Output directory for MaxEnt
    $layersDirectory = __DIR__ . '/../resources/coverages'; // Output directory for MaxEnt

    // Path to the input file for MaxEnt
    $inputFilePath = $outputDirectory . 'alltest.csv';

    // Prepare the command to run MaxEnt. Adjust paths and parameters as necessary. Here instead of just starting with "java" you might need to directly use something like "/home/user/.sdkman/candidates/java/22-amzn/bin/java"
    $command = escapeshellcmd("java -mx512m -Djava.awt.headless=true -jar \"$maxEntJarPath\" environmentallayers=$layersDirectory samplesfile=\"$inputFilePath\" outputdirectory=\"$outputDirectory\" pictures redoifexists autorun visible=false");
    $command .= " 2>&1"; // Redirect stderr to stdout for comprehensive output capture
    
    // Execute MaxEnt and capture the output. Note: shell_exec() does not allow capturing return status.
    exec($command, $output, $returnVar);

    // Check execution status and log the output
    if ($returnVar !== 0) {
        echo "Command failed with status $returnVar:\n";
        foreach ($output as $line) {
            echo "$line\n";
        }
        return false;
    } else {
        echo "Command succeeded:\n";
        foreach ($output as $line) {
            echo "$line\n";
        }
    }
}

run_maxent();
?>
```

And that's it problem solved and working in a Headless server! :)
